name: Deployment pipeline
on:
  push:
    branches:
      - main
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build:ui
      - name: test
        run: npm run test
        env:
          TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
          PORT: ${{secrets.PORT}}
          SECRET: ${{secrets.SECRET}}
      - name: e2e tests
        uses: cypress-io/github-action@v2
        env:
          TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
          PORT: ${{secrets.PORT}}
          SECRET: ${{secrets.SECRET}}
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3003