name: Deployment pipeline
on:
  push:
    branches:
      - main
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build:ui
      - name: test
        run: npm run test
        env:
          TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
          PORT: ${{secrets.PORT}}
          SECRET: ${{secrets.SECRET}}
      - name: e2e tests
        uses: cypress-io/github-action@v2
        env:
          TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
          PORT: ${{secrets.PORT}}
          SECRET: ${{secrets.SECRET}}
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3003
      - name: heroku deploy
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')}}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: fuzzy-pancake
          heroku_email: ${{secrets.HEROKU_EMAIL}}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')}}
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          